Combi19/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', include('Combi19App.urls')),
    path('', include('users.urls')),
    path('', include('tienda.urls')),
    path('carro/', include('carro.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from .import views

app_name="carro"

urlpatterns = [
    # path('', views.home, name="Home"),
    # path('', views.about, name ="About"),
    # path('', views.tienda, name="Insumos"),
    # path('', views.pasajes, name="Pasajes"),
    # path('', views.contacto, name="Contacto"),
    # path('', views.suscripcion, name="Suscripcion"),
    # path('', views.comprar_pasaje, name = "Comprar Pasaje"),
    path('agregar/<int:insumo_id>', views.agregar_insumo, name="agregar"),
    path('eliminar/<int:insumo_id>', views.eliminar_insumo, name="eliminar"),
    path('restar/<int:insumo_id>', views.restar_insumo, name="restar"),
    path('limpiar/', views.limpiar_carrito, name="limpiar"),

]

tienda/urls.py
from django.urls import path
from .import views
from users import views as UserViews

urlpatterns = [
    path('home', views.home, name="Home"),
    path('nosotros', views.about, name ="About"),
    path('tienda', views.tienda, name="Insumos"),
    path('pasajes', views.pasajes, name="Pasajes"),
    path('contacto', views.contacto, name="Contacto"),
    path('suscripcion', views.suscripcion, name="Suscripcion"),
    path ('pasajes/comprar<v_id>', views.comprar_pasaje, name = "Comprar Pasaje"),
    path ('tienda/comprar', views.comprar_insumos, name = "Comprar Insumo"),
    path('', views.index, name="Index")
    
]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models
from django.core.validators import MinValueValidator
# Create your models here.
class Insumo(models.Model):
    nombre        = models.CharField(max_length=30)
    descripcion   = models.CharField(max_length=50)
    precio        = models.IntegerField(validators=[MinValueValidator(0)])
    imagen        = models.ImageField(upload_to="insumos", null=True)
    cantidad      = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(0)])
    created       = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated       = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return f'{self.nombre}'

    def restar_insumo(self, comprados):
        self.cantidad = self.cantidad - comprados

tienda/forms.py
from django import forms
from Combi19App.models import Viaje


class CompraPasajeForm(forms.ModelForm):
    class Meta:
        model = Viaje
        fields = ("asientos_ocupados",)

    def clean_asientos_ocupados(self):
        asientos = self.cleaned_data['asientos_ocupados']
        return asientos

carro/views.py
from django.shortcuts import render

from.carro import Carro

from tienda.models import Insumo

from django.shortcuts import redirect

# Create your views here.

def agregar_insumo(request, insumo_id):
    
    carro=Carro(request)
    
    insumo=Insumo.objects.get(id=insumo_id)
    
    carro.agregar(insumo=insumo)
    
    return redirect("Insumos")


def eliminar_insumo(request, insumo_id):
    
    carro=Carro(request)
    
    insumo=Insumo.objects.get(id=insumo_id)
    
    carro.eliminar(insumo=insumo)
    
    return redirect("Insumos")

def restar_insumo(request, insumo_id):
    
    carro=Carro(request)
    
    insumo=Insumo.objects.get(id=insumo_id)
    
    carro.restar_producto(insumo=insumo)
    
    return redirect("Insumos")


def limpiar_carrito(request):
    
    carro=Carro(request)
    
    carro.limpiar_carro()
    
    return redirect("Insumos")

tienda/views.py
from users.models import Tarjeta
from Combi19App.models import Viaje, Pasaje
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from Combi19App.filters import ViajeFilter
from django.db.models import F
from .models import Insumo

from Combi19App.forms import CompraPasajeForm

# Aca creamos nuestras vistas.
@login_required
def home (request):
    return render(request, "Combi19App/home.html")

@login_required
def pasajes (request):
    viajes = Viaje.objects.all().filter(asientos_ocupados__lt= F('combi__capacidad') )

    miFiltro = ViajeFilter(request.GET, queryset=viajes)

    viajes = miFiltro.qs

    context = {"viajes": viajes, 'miFiltro': miFiltro}
    return render(request, "Combi19App/pasajes.html", context)


@login_required
def comprar_pasaje(request, *args, **kwargs):
    viaje_id = kwargs.get("v_id")
    try: 
        viaje = Viaje.objects.get(pk = viaje_id)
    except:
        return HttpResponse("Hubo un error")

    try: 
        tarjetas_usuario = Tarjeta.objects.filter(usuario_id=request.user.id)
    except Exception as E: #No tenemos tarjetas
        return redirect("Tarjetas")

    if request.user.is_GOLD:
        precio = viaje.precio * 0.1
    else:
        precio = viaje.precio

    context = {"viaje": viaje, "tarjetas": tarjetas_usuario, "precio": precio}


    
    if request.POST:
        form = CompraPasajeForm(request.POST)
        if form.is_valid():
            ocupados = int(form.cleaned_data.get('asientos_ocupados'))
            viaje.asientos_ocupados= F('asientos_ocupados') + ocupados
            viaje.pasajeros.add(request.user)
            viaje.save()
            viaje.refresh_from_db()
            
            p = Pasaje(viaje=viaje, usuario=request.user)
            p.save()
        return redirect("Compra Exitosa")
    
    return render(request, "Combi19App/detalle_viaje.html", context)

@login_required
def contacto (request):
    return render(request, "Combi19App/contact.html")

@login_required
def about (request):
    return render(request, "Combi19App/about.html")
    
def index (request):
    if request.user.is_authenticated:
        return render(request, "Combi19App/home.html")
    return render(request, "Combi19App/index.html")

@login_required
def suscripcion (request):
    return render(request, "Combi19App/pricing.html")

@login_required
def tienda (request):
    insumos = Insumo.objects.all()
    return render(request, "tienda/insumos.html", {"insumos": insumos})

@login_required
def comprar_insumos(request, *args, **kwargs):
    tarjetas_usuario = Tarjeta.objects.filter(usuario_id=request.user.id)
    if not tarjetas_usuario:
        return redirect("Tarjetas")

    carrito = request.session['carro']
    viajes = Viaje.objects.filter(pasajeros=request.user).filter(estado=Viaje.comenzado)
    context = {"viajes":viajes}

    if request.POST:
        d = dict(carrito.items())
        for each in d.values():
            insumo = Insumo.objects.get(id=each["insumo_id"])
            insumo.restar_insumo(each["cantidad"])
            insumo.save()
            return redirect("Insumo Exitoso")


    return render(request, "tienda/detalle_insumo.html", context)

tienda/templates/carro/widget.html
<table class= "table table-bordered" style="color: black;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                CARRO DE COMPRAS
            </th>
        </tr>
        <tr>
            <th>Insumo</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key,value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.insumo_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.insumo_id %}" class="btn btn-sm btn-success">-</a><br/>
                        ${{value.precio}}
                        
                    </td>
                
                </tr>
            {%endfor%}
        {%else%}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No hay insumos agregados
                    </div>
                </td>
            </tr>
        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                <h6 class="">TOTAL:{{importe_total}}</h6>
                {% if importe_total > 0  %}  
                    <a href="{% url 'Comprar Insumo'  %}">
                        <span class="btn btn-outline-success rounded-pill light-300  right">
                            Comprar 
                            <i class='bx bxs-cart-add'></i>
                        </span>
                    </a>
                {% endif %}
                <a href="{% url 'carro:limpiar'  %}">
                    <span class="btn btn-outline-danger rounded-pill light-300right">
                        Limpiar
                        <i class='bx bxs-cart-add'></i>
                    </span>
                </a>
            </td>
        </tr>
    </tfoot>

</table>