Combi19/urls.py
from django.contrib import admin
from django.urls import path, include  
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', include('Combi19App.urls')),
    path('', include('users.urls')),
    path('', include('tienda.urls')),
    path('carro/', include('carro.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Combi19App/urls.py
from django.urls import path
from Combi19App import views
from users import views as UserViews

urlpatterns = [
    path('home', views.home, name="Home"),
    path('nosotros', views.about, name ="About"),
    path('pasajes', views.pasajes, name="Pasajes"),
    path('contacto', views.contacto, name="Contacto"),

    path('suscripcion', views.suscripcion, name="Suscripcion"),
    path('suscripcion/gold', views.suscripcion_gold_exito, name="GOLD"),
    path('suscripcion/cancelargold', views.suscripcion_gold_chau, name="NO-GOLD"),

    path('exito', views.compra_exitosa, name="Compra Exitosa"),

    path('reseñas', views.reseñas, name="Reseñas"),
    path ('reseñas/eliminar<c_id>', views.delete_comentario, name = "Eliminar Comentario"),
    path ('reseñas/editar<c_id>', views.modificar_comentario, name = "Editar Comentario"),

    path('tienda/exito', views.insumo_exitoso, name="Insumo Exitoso"),
    path ('pasajes/comprar<v_id>', views.comprar_pasaje, name = "Comprar Pasaje"),
    path ('pasajes/comprar<v_id>/<p_id>', views.comprar_pasaje_chofer, name = "Comprar Pasaje Chofer"),
    path('', views.index, name="Index")
    
]

carro/urls.py
from django.urls import path
from .import views

app_name="carro"

urlpatterns = [
    # path('', views.home, name="Home"),
    # path('', views.about, name ="About"),
    # path('', views.tienda, name="Insumos"),
    # path('', views.pasajes, name="Pasajes"),
    # path('', views.contacto, name="Contacto"),
    # path('', views.suscripcion, name="Suscripcion"),
    # path('', views.comprar_pasaje, name = "Comprar Pasaje"),
    path('agregar/<int:insumo_id>', views.agregar_insumo, name="agregar"),
    path('eliminar/<int:insumo_id>', views.eliminar_insumo, name="eliminar"),
    path('restar/<int:insumo_id>', views.restar_insumo, name="restar"),
    path('limpiar/', views.limpiar_carrito, name="limpiar"),

]

Combi19App/models.py
from django.db import models
from django.db.models.expressions import F
from django.db.models.constraints import UniqueConstraint
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from tienda.models import Insumo
# Create your models here.
from users.models import Account, Chofer

class Vehiculo(models.Model):

    patente       = models.CharField(max_length=10, unique=True)
    capacidad     = models.IntegerField(validators=[MinValueValidator(0)])
    modelo        = models.IntegerField()
    chofer        = models.ForeignKey(Chofer, blank=True, null=True, default=None, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.patente

class Lugar(models.Model):
    nombre        = models.CharField(max_length=40, blank=True, null=True, unique=True, verbose_name='Lugar')
    provincia     = models.CharField(max_length=20, blank=True, null=True)
    codigo_postal = models.IntegerField(blank=True, null=True, unique=True, validators=[MinValueValidator(1000)])
    imagen        = models.ImageField(upload_to="ciudades", blank=True, null=True)
    class Meta:
        verbose_name_plural = "Lugares"
        

    def __str__(self):
        return f'{self.nombre}'

class Ruta(models.Model):
    origen        = models.ForeignKey(Lugar, default=None, on_delete=models.CASCADE, related_name='origen')
    destino       = models.ForeignKey(Lugar, default=None, on_delete=models.CASCADE, related_name='destino')
    nombre        = models.CharField(max_length=30, blank=True, null=True, verbose_name='Nombre de ruta')
    km            = models.IntegerField(validators=[MinValueValidator(0)])

    def clean(self):
        if self.origen==self.destino:
            raise ValidationError('Los campos no pueden coincidir')
    

    class Meta:
        unique_together = ('origen', 'destino')
        
    def __str__(self):
        return f'De {self.origen} a {self.destino}'

class Comentario(models.Model):
    usuario    = models.ForeignKey(Account, default=None, null=True,on_delete=models.CASCADE)
    comentario = models.CharField(max_length=300)
    ruta       = models.ForeignKey(Ruta, default=None, null=True,on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.usuario}: {self.comentario}"

class Viaje(models.Model):
    comenzado  = "com"
    finalizado = "fin"
    cancelado  = "can"
    ESTADO_CHOICES = [ (comenzado,'COMENZADO'), (finalizado, 'FINALIZADO'), (cancelado,'CANCELADO') ]
    
    
    fecha             =   models.DateTimeField(blank=True, null=True)
    ruta              =   models.ForeignKey(Ruta, default=None, blank=True, null=True, on_delete=models.CASCADE)
    combi             =   models.ForeignKey(Vehiculo, blank=True, null=True, on_delete=models.CASCADE)
    precio            =   models.DecimalField(default=None, blank=True, null=True, max_digits=10, decimal_places=2)
    insumo            =   models.ManyToManyField(Insumo,default=None, blank=True)
    pasajeros         =   models.ManyToManyField(Account, default=None, blank=True)
    asientos_ocupados =   models.IntegerField(default=0, null=True, blank=True)
    estado            =   models.CharField(max_length=3, choices=ESTADO_CHOICES, default=ESTADO_CHOICES[0])
    
    class Meta:
        unique_together = ('fecha', 'combi')
        
    def __str__(self):
        return f'Fecha: {self.fecha:%Y-%m-%d %H:%M} - Ruta: {self.ruta} - Combi: {self.combi} '

    def finalizar_viaje(self):
        self.estado = self.finalizado
    
    def cancelar_viaje(self):
        self.estado = self.cancelado

class Pasaje(models.Model):
    pendiente  = "pen"
    finalizado = "fin"
    cancelado  = "can"
    ESTADO_CHOICES = [ (pendiente,'PENDIENTE'), (finalizado, 'FINALIZADO'), (cancelado,'CANCELADO') ]
    
    viaje    = models.ForeignKey(Viaje, on_delete=models.CASCADE)
    usuario  = models.ForeignKey(Account, on_delete=models.CASCADE)
    cantidad = models.IntegerField(blank=True, null=True)
    estado   = models.CharField(max_length=3, choices=ESTADO_CHOICES, default=ESTADO_CHOICES[0])

    class Meta:
        verbose_name_plural = "Pasajes"

class Testeo(models.Model):
    usuario                 = models.ForeignKey(Account, on_delete=models.CASCADE)
    viaje                   = models.ForeignKey(Viaje, on_delete=models.CASCADE, blank=True, null=True)
    temperatura             = models.FloatField()
    dolor_cabeza            = models.BooleanField()
    dolor_garganta          = models.BooleanField()
    dolor_muscular          = models.BooleanField()
    vomitos_diarrea         = models.BooleanField()
    perdida_gusto_olfato    = models.BooleanField()
    tos                     = models.BooleanField()
    dificultad_respiratoria = models.BooleanField()
    cantidad                = models.IntegerField(verbose_name='Cantidad de sintomas', blank=True, null=True)

    class Meta:
        verbose_name_plural = "Testeos"

Combi19App/views.py
from users.models import Account, Tarjeta
from Combi19App.models import Comentario, Viaje, Pasaje, Ruta
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from .filters import ViajeFilter, ComentarioFilter
from django.db.models import F

from Combi19App.forms import CompraPasajeForm, ComentarioForm, EditarComentarioForm

# Aca creamos nuestras vistas.
@login_required
def home (request):
    return render(request, "Combi19App/home.html")

@login_required
def pasajes (request):
    viajes = Viaje.objects.all().filter(asientos_ocupados__lt= F('combi__capacidad') ).filter(estado=Viaje.comenzado)

    miFiltro = ViajeFilter(request.GET, queryset=viajes)

    viajes = miFiltro.qs

    context = {"viajes": viajes, 'miFiltro': miFiltro}
    return render(request, "Combi19App/pasajes.html", context)

@login_required
def comprar_pasaje(request, *args, **kwargs):
    viaje_id = kwargs.get("v_id")
    try: 
        viaje = Viaje.objects.get(pk = viaje_id)
    except:
        return HttpResponse("Hubo un error")

    tarjetas_usuario = Tarjeta.objects.filter(usuario_id=request.user.id)

    if not (request.user.es_chofer) and not tarjetas_usuario:
        return redirect("Tarjetas")

    if request.user.is_GOLD:
        precio = int(viaje.precio) - int(viaje.precio) * 0.1
    else:
        precio = viaje.precio

    context = {"viaje": viaje, "tarjetas": tarjetas_usuario, "precio": precio}


    
    if request.POST:
        form = CompraPasajeForm(request.POST)
        if form.is_valid():
            ocupados = int(form.cleaned_data.get('asientos_ocupados'))
            viaje.asientos_ocupados= F('asientos_ocupados') + ocupados
            viaje.pasajeros.add(request.user)
            viaje.save()
            viaje.refresh_from_db()
            
            p = Pasaje(viaje=viaje, usuario=request.user, cantidad=ocupados, estado=Pasaje.pendiente)
            p.save()
        return redirect("Compra Exitosa")
    
    return render(request, "Combi19App/detalle_viaje.html", context)

@login_required
def comprar_pasaje_chofer(request, *args, **kwargs):
    viaje_id = kwargs.get("v_id")
    try: 
        viaje = Viaje.objects.get(pk = viaje_id)
    except:
        return HttpResponse("Hubo un error")
    
    usuario_id = kwargs.get("p_id")
    try: 
        usuario = Account.objects.get(pk = usuario_id)
    except:
        return HttpResponse("Hubo un error")

    context = {"viaje": viaje, "usuario":usuario}

    if request.POST:
        form = CompraPasajeForm(request.POST)
        if form.is_valid():
            ocupados = int(form.cleaned_data.get('asientos_ocupados'))
            viaje.asientos_ocupados= F('asientos_ocupados') + ocupados
            viaje.pasajeros.add(usuario)
            viaje.save()
            viaje.refresh_from_db()
            
            p = Pasaje(viaje=viaje, usuario=usuario, cantidad=ocupados)
            p.save()
        return redirect("Compra Exitosa")
    
    return render(request, "Combi19App/detalle_viaje_chofer.html", context)

@login_required
def suscripcion_gold_exito(request):
    tarjetas = Tarjeta.objects.filter(usuario_id=request.user.id)

    if not tarjetas:
        return redirect("Tarjetas")

    usuario = request.user
    usuario.is_GOLD = True
    usuario.save()
    usuario.refresh_from_db()
    
    return render(request, "Combi19App/goldexito.html")

@login_required
def suscripcion_gold_chau(request):

    usuario = request.user
    usuario.is_GOLD = False
    usuario.save()
    usuario.refresh_from_db()
    
    return render(request, "Combi19App/usuarionormalexito.html")

@login_required
def compra_exitosa(request):
    return render(request, "Combi19App/exito.html")

@login_required
def insumo_exitoso(request):
    return render(request, "Combi19App/exitoinsumo.html")

@login_required
def contacto (request):
    return render(request, "Combi19App/contact.html")

@login_required
def about (request):
    return render(request, "Combi19App/about.html")
    
def index (request):
    if request.user.is_authenticated:
        return render(request, "Combi19App/home.html")
    return render(request, "Combi19App/index.html")

@login_required
def suscripcion (request):
    return render(request, "Combi19App/pricing.html")

@login_required
def comprar_insumos(request, *args, **kwargs):
    carrito = kwargs.get("carrito")

@login_required
def reseñas(request):
    com = Comentario.objects.all()

    mis_viajes = Viaje.objects.filter(pasajeros=request.user).filter(estado=Viaje.finalizado)
    rutas = Ruta.objects.filter(viaje__in=mis_viajes)


    miFiltro = ComentarioFilter(request.GET, queryset=com)
    com = miFiltro.qs
    form = ComentarioForm(instance=request.user)


    if request.POST:
        form = ComentarioForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        else:
            pass

    context = {"comentarios": com, 'miFiltro': miFiltro, 'rutas':rutas, 'form':form }
    return render(request, "Combi19App/reseñas.html", context)

def modificar_comentario(request, *args, **kwargs):
    c_id = kwargs.get("c_id")
    try:
        comentario = Comentario.objects.get(pk=c_id)
    except Tarjeta.DoesNotExist:
        return HttpResponse("Hubo un error")

    form = EditarComentarioForm(instance=comentario)
    context = {"comentario":comentario, "form": form}

    if request.POST:
        form = EditarComentarioForm(request.POST, instance=comentario)
        if form.is_valid():
            form.save()
            return redirect("Reseñas")
        
    return render(request, "Combi19App/modificar_comentario.html", context)
    
def delete_comentario(request, *args, **kwargs):
    c_id = kwargs.get("c_id")
    try:
        comentario = Comentario.objects.get(pk=c_id)
    except Tarjeta.DoesNotExist:
        return HttpResponse("Hubo un error")
    context = {"comentario":comentario}

    if request.POST:
        comentario.delete()
        return redirect("Reseñas")

    return render(request, "Combi19App/eliminar_comentario.html", context)

Combi19App/templates/Combi19App/about.html
{% extends 'Combi19App/base.html' %}
{%load static%}
{% block content %}

    <!-- Start Banner Hero -->
    <section class="bg-light w-100">
        <div class="container">
            <div class="row d-flex align-items-center py-5">
                <div class="col-lg-6 text-start">
                    <h1 class="h2 py-5 text-primary typo-space-line">Sobre Nosotros</h1>
                    <p class="light-300">
                        Somos una empresa de venta de pasajes en combi a diversos destinos de Argentina.
                        Nuestro nombre viene de la respuesta que le dimos a la problemática de <strong>viajar en tiempos de pandemia</strong>.
                    </p>
                </div>
                <div class="col-lg-6">
                    <img src="{% static 'Combi19App/img/Journey-amico.svg' %}">
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Hero -->

    <!-- Start Choice -->
    <section class="why-us banner-bg bg-light">
        <div class="container my-4">
            <div class="row">
                <div class="banner-img col-lg-5">
                    <img src="{% static 'Combi19App/img/Resume-amico.svg' %}" class="rounded img-fluid" alt="">
                </div>
                <div class="banner-content col-lg-7 align-self-end">
                    <h2 class="h2 pb-3">¿Por qué Elegirnos?</h2>
                    <p class="text-muted pb-5 light-300">    Porque somos mucho más que una empresa de viajes, prestamos un servicio integral al usuario, para que el mismo no tenga que preocuparse de nada.
                        <br>    Por nuestra efectividad, aseguramos una experiencia única.
                        <br>    Porque junto con los choferes que conforman nuestra empresa, somos un equipo que trabaja para asegurar la satisfacción de nuestros clientes.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End Choice -->

    <!-- Start Team Member -->
    <section class="container py-5">
        <div class="pt-5 pb-3 d-lg-flex align-items-center gx-5">

            <div class="col-lg-3">
                <h2 class="h2 py-5 typo-space-line">Nuestros Servicios</h2>
                <p class="text-muted ">
                    Nos encargamos de estos 3 aspectos fundamentales en todo viaje (hoy en día).
                </p>
            </div>

            <div class="col-lg-9 row">
                <div class="team-member col-md-4">
                    <img class="team-member-img img-fluid rounded-circle p-4" src="{% static 'Combi19App/img/Insumo1.jpg' %}" alt="Foto insumos">
                    <ul class="team-member-caption list-unstyled text-center pt-4 text-muted light-300">
                        <li><b>Venta de insumos para tu viaje</b></li>
                        <li>Bebida, comida y varios</li>
                    </ul>
                </div>
                <div class="team-member col-md-4">
                    <img class="team-member-img img-fluid rounded-circle p-4" src="{% static 'Combi19App/img/woman-with-tickets-giving-thumb-up.jpg' %}" alt="Card image">
                    <ul class="team-member-caption list-unstyled text-center pt-4 text-muted light-300">
                        <li><b>Venta de pasaje/s</b></li>
                        <li>Elegí de nuestros viajes disponibles</li>
                    </ul>
                </div>
                <div class="team-member col-md-4">
                    <img class="team-member-img img-fluid rounded-circle p-4" src="{% static 'Combi19App/img/teacher-with-medical-mask-checking-children-s-temperature-school.jpg' %}" alt="Card image">
                    <ul class="team-member-caption list-unstyled text-center pt-4 text-muted light-300">
                        <li><b>Testeos de Síntomas</b></li>
                        <li>Sólo suben personas sin estos</li>
                    </ul>
                </div>
            </div>

        </div>
    </section>
    <!-- End Team Member -->

    <!-- Start Our Partner -->
    <section class="bg-secondary py-3">
        <div class="container py-5">
            <h2 class="h2 text-white text-center py-5">Garantizamos</h2>
            <div class="row text-center text-light">
                <div class="col-md-3 mb-3">
                    <div class="card partner-wap pt-5 pb-4">
                        <a href="#"><i class='display-1 text-white bx bxs-bus'></i></a>
                        <p class="light-300 pt-1 px-2">Llegar a destino a tiempo</p>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="card partner-wap pt-5 pb-4">
                        <a href="#"><i class='display-1 bx text-white bx bx-accessibility'></i></a>
                        <p class="light-300 pt-1 px-2">Viaje accesible</p>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="card partner-wap  pt-5 pb-4">
                        <a href="#"><i class='display-1 text-white bx bxs-virus-block'></i></a>
                        <p class="light-300 pt-1 px-2">Protocolo de transporte</p>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="card partner-wap  pt-5 pb-4">
                        <a href="#"><i class='display-1 text-white bx bx-dollar'></i></a>
                        <p class="light-300 pt-1 px-2">Precios amigos</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!-- Start Aim -->
    <section class="banner-bg bg-white py-5">
        <div class="container my-4">
            <div class="row text-center">

                <div class="objective col-lg-4">
                    <div class="objective-icon card m-auto py-4 mb-2 mb-sm-4 bg-secondary shadow-lg">
                        <i class="display-4 bx bxs-bulb text-light"></i>
                    </div>
                    <h2 class="objective-heading h3 mb-2 mb-sm-4 light-300">Nuestra Vision</h2>
                    <p class="light-300">
                        Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse commodo viverra.
                    </p>
                </div>

                <div class="objective col-lg-4 mt-sm-0 mt-4">
                    <div class="objective-icon card m-auto py-4 mb-2 mb-sm-4 bg-secondary shadow-lg">
                        <i class='display-4 bx bx-revision text-light'></i>
                    </div>
                    <h2 class="objective-heading h3 mb-2 mb-sm-4 light-300">Nuestra Misión</h2>
                    <p class="light-300">
                        Eiusmod tempor incididunt ut labore et dolore magna aliqua.
                        Ut enim ad minim veniam quis.
                    </p>
                </div>

                <div class="objective col-lg-4 mt-sm-0 mt-4">
                    <div class="objective-icon card m-auto py-4 mb-2 mb-sm-4 bg-secondary shadow-lg">
                        <i class="display-4 bx bxs-select-multiple text-light"></i>
                    </div>
                    <h2 class="objective-heading h3 mb-2 mb-sm-4 light-300">Nuestra Pasión</h2>
                    <p class="light-300">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor.
                    </p>
                </div>

            </div>
        </div>
    </section>
    <!-- End Aim -->



    <!-- Bootstrap -->
     <!-- Bootstrap core JS-->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js "></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js "></script>
     <!-- Third party plugin JS-->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js "></script>
     <!-- Bootstrap -->
     <script src="{% static 'Combi19App/js/bootstrap.bundle.min.js' %}"></script>
     <!-- Load jQuery require for isotope -->
     <script src="{% static 'Combi19App/js/jquery.min.js' %}"></script>
    {% endblock %}

Combi19App/templates/Combi19App/exitoinsumo.html
{% extends 'Combi19App/base.html' %}

{% load static %}
{% block content %}


<div class="my-5 mx-5 card">
    <h5 class="card-header semi-bold-600">¡Compra exitosa!</h5>
    <div class="card-body">
        <h5 class="card-title semi-bold-600">Felicidades {{request.user.first_name}}. Disfrutá de esto en tu viaje.</h5>
        <p class="card-text light-300">Recordá que podés visualizar tus futuros viajes en las opciones de usuario <span><i class='bx bx-user-circle bx-sm text-primary'></i></span>, clickeando en la pestaña "Mis Viajes".</p>
        <a href="{% url 'Home' %}" class="btn rounded-pill btn-outline-primary">Continuar</a>
        </form>
    </div>
  </div>

 <!-- Bootstrap core JS-->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js "></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js "></script>
 <!-- Third party plugin JS-->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js "></script>
 <!-- Bootstrap -->
 <script src="{% static 'Combi19App/js/bootstrap.bundle.min.js' %}"></script>
 <!-- Load jQuery require for isotope -->
 <script src="{% static 'Combi19App/js/jquery.min.js' %}"></script>
{% endblock %} 

Combi19App/templates/Combi19App/reseñas.html
{% extends 'Combi19App/base.html' %}
{% load poll_extras %}
{% load bootstrap %}
{% load static %}
{% block content %}
<section class="bg-light">
    <div class="container py-4">
        <div class="row align-items-center justify-content-between">
            <div class="contact-header col-lg-4">
                <h1 class="h1 pb-4 text-primary">Ayudanos a crecer</h1>
                <h3 class="h3 regular-400">Dejanos tu opinión</h3>
                <p class="light-300">
                    <i class='bx bx-happy'></i>
                    ¿Tuviste algún problema en tu viaje? 
                    <br>
                    <i class='bx bx-comment' ></i>
                    ¿Querés compartir la experiencia que tuviste? 
                    <br>
                    <i class='bx bx-mail-send' ></i>
                    A rellenar
                </p>
            </div>
            <div class="contact-img col-lg-5 align-items-end col-md-4">
                <img src="{% static 'Combi19App/img/Feedback-amico.svg' %}"
            </div>
        </div>
    </div>
</section>
<section class="container py-5">
    <h3 class="h3"> Agregá tu reseña</h3>
    <div class="col-md-12 ">
        <form class="contact-form row" method="post" action="#" role="form"> {% csrf_token %}
            <input type="hidden">
            <div class="form-group">
                <label class="control-label  " for="id_ruta">Ruta</label>
                <div class=" ">
                        <select name="ruta" class=" form-control" required="" id="id_ruta">
                            {% for r in rutas %}
                                <option value={{r.id}}>{{r}}</option>
                            {% endfor %}
                        </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label  " for="id_comentario">Comentario</label>
                    <div class=" ">
                        <input type="text" name="comentario" maxlength="300" class=" form-control" required="" id="id_comentario">
                    </div>
            </div>
                <div class="py-4">
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Añadir comentario</button>
                    </div>
                </div>
        </form>
    </div>
    
    <hr>
</section>

<section class="py-5 ">
    <div class="container">
        
        <h3 class="h3">Buscá reseñas sobre tu próximo viaje</h3>
        <form class="form-control " id="formularioFiltros" method="get" action="#" role="form">
            <div class="row gy-5 g-lg-5 ">
                <div class="col-md-9 pb-4">
                    {{miFiltro.form|bootstrap}}
                </div>
                <div class="col-md-3 pt-4">
                    <button type="submit" class="btn btn-secondary rounded-pill px-md-5 px-4 py-2 radius-0 text-light light-300">Buscar viaje</button>
                </div>
            </div>
        </form>
</section>

<section class="py-3 mb-3">
    <div class="container">
        <div class="row gy-5 g-lg-5 mb-4"> 
            {% if miFiltro.qs %}
                {%  for c in miFiltro.qs %}
                    <div class="col-xl-6 col-md-12 col-sm-12">
                        <div  class="card bg-light border-0 shadow-lg overflow-hidden">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12 px-3">
                                        <h5 class="h5">{{c.usuario}}</h5>
                                        <p class="semi-bold-600 text-muted">Desde: {{c.ruta.origen}} hasta: {{c.ruta.destino}}</p>
                                        <p class="light-300 "style="height: 3em;">{{c.comentario}}</p>
                                    </div>
                                    {% if c.usuario == request.user %}
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{% url 'Editar Comentario' c_id=c.id %}"><button type="button" class="btn btn-primary px-4">Editar</button></a>
                                        <a href="{% url 'Eliminar Comentario' c_id=c.id %}"><button type="button" class="btn btn-primary px-4">Eliminar</button></a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div><!-- End Recent Work -->
                {%  endfor %}
            {% else %}
                    <p>No hay comentarios para los datos indicados</p>
            {% endif %}
        </div>
        
    </div>
</section>
 <!-- Bootstrap core JS-->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js "></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js "></script>
 <!-- Third party plugin JS-->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js "></script>
 <!-- Bootstrap -->
 <script src="{% static 'Combi19App/js/bootstrap.bundle.min.js' %}"></script>
 <!-- Load jQuery require for isotope -->
 <script src="{% static 'Combi19App/js/jquery.min.js' %}"></script>
{% endblock %} 